### PR TITLE
Add Path block rotation variants

### LINKED ISSUE #5: Top texture grass is not like vanilla
I have absolutly no idea what cause this bug

### PR DESCRIPTION
**Pull request by Fourmisain**
As mentioned, this should fix #5.
Give it some testing to make sure Path blocks actually load with this change!

### CODE REVIEW

**Comment by lebonq** [comment]
Oh thanks you I will try this soon as possible !

**Comment by lebonq** [comment]
I tried it and it looks like it works but if you can double check for me thats would be great !

**Comment by lebonq** [comment]
Ok, I have seen you already test it so I merge this! Thank you I was struggling with this one for a long time :(

**Comment by Fourmisain** [comment]
To make sure tested it once more, I created a new world on the old version, converted a few grass blocks to path, recompiled this and loaded it in the new version and everything was fine - it even showed the variations on already existing blocks!

(And I did this before your last message 😄)

**Pull request merged**
